item-default-value: 1.0
final-scale: 1.0
final-score-cap: 100

# --------------- enchantments ---------------
enchantment-default-value: 0.5
enchantment-level-scale: 1

enchantments:
  ARROW_DAMAGE:
  ARROW_FIRE:
  ARROW_INFINITE:
  ARROW_KNOCKBACK:
  BINDING_CURSE:
  CHANNELING:
  DAMAGE_ALL:
  DAMAGE_ARTHROPODS:
  DAMAGE_UNDEAD:
  DEPTH_STRIDER:
  DIG_SPEED:
  DURABILITY:
  FIRE_ASPECT:
  FROST_WALKER:
  IMPALING:
  KNOCKBACK:
  LOOT_BONUS_BLOCKS:
  LOOT_BONUS_MOBS:
  LOYALTY:
  LUCK:
  LURE:
  MENDING:
  MULTISHOT:
  OXYGEN:
  PIERCING:
  PROTECTION_ENVIRONMENTAL:
  PROTECTION_EXPLOSIONS:
  PROTECTION_FALL:
  PROTECTION_FIRE:
  PROTECTION_PROJECTILE:
  QUICK_CHARGE:
  RIPTIDE:
  SILK_TOUCH:
  SOUL_SPEED:
  SWEEPING_EDGE:
  SWIFT_SNEAK:
  THORNS:
  VANISHING_CURSE:
  WATER_WORKER:

# --------------- armors ----------------

materials:
  LEATHER_HELMET: 1
  LEATHER_CHESTPLATE: 1
  LEATHER_LEGGINGS: 1
  LEATHER_BOOTS: 1

  CHAINMAIL_HELMET: 2
  CHAINMAIL_CHESTPLATE: 2
  CHAINMAIL_LEGGINGS: 2
  CHAINMAIL_BOOTS: 2

  IRON_HELMET: 3
  IRON_CHESTPLATE: 3
  IRON_LEGGINGS: 3
  IRON_BOOTS: 3

  GOLD_HELMET: 4
  GOLD_CHESTPLATE: 4
  GOLD_LEGGINGS: 4
  GOLD_BOOTS: 4

  DIAMOND_HELMET: 5
  DIAMOND_CHESTPLATE: 5
  DIAMOND_LEGGINGS: 5
  DIAMOND_BOOTS: 5

  NETHERITE_HELMET: 6
  NETHERITE_CHESTPLATE: 6
  NETHERITE_LEGGINGS: 6
  NETHERITE_BOOTS: 6

# --------------- weapons ----------------

  STONE_SWORD: 1
  IRON_SWORD: 2
  GOLD_SWORD: 3
  DIAMOND_SWORD: 4
  NETHERITE_SWORD: 5

  STONE_AXE: 1
  IRON_AXE: 2
  GOLD_AXE: 3
  DIAMOND_AXE: 4
  NETHERITE_AXE: 5

  BOW: 2
  CROSSBOW: 3
