item-default-value: 1.0
final-scale: 1.0
final-score-cap: 100

check-main-hand: true
check-offhand-hand: true
check-armor: true

# --------------- enchantments ---------------
enchantment-default-value: 0.5
enchantment-level-scale: 1

enchantments:
  AQUA_AFFINITY:
  BANE_OF_ARTHROPODS:
  BINDING_CURSE:
  BLAST_PROTECTION:
  CHANNELING:
  DEPTH_STRIDER:
  EFFICIENCY:
  FEATHER_FALLING:
  FIRE_ASPECT:
  FIRE_PROTECTION:
  FLAME:
  FORTUNE:
  FROST_WALKER:
  IMPALING:
  INFINITY:
  KNOCKBACK:
  LOOTING:
  LOYALTY:
  LUCK_OF_THE_SEA:
  LURE:
  MENDING:
  MULTISHOT:
  PIERCING:
  POWER:
  PROJECTILE_PROTECTION:
  PROTECTION:
  PUNCH:
  QUICK_CHARGE:
  RESPIRATION:
  RIPTIDE:
  SHARPNESS:
  SILK_TOUCH:
  SMITE:
  SOUL_SPEED:
  SWEEPING:
  SWIFT_SNEAK:
  THORNS:
  UNBREAKING:
  VANISHING_CURSE: 0

# --------------- armors ----------------

materials:
  LEATHER_HELMET: 1
  LEATHER_CHESTPLATE: 1
  LEATHER_LEGGINGS: 1
  LEATHER_BOOTS: 1

  CHAINMAIL_HELMET: 2
  CHAINMAIL_CHESTPLATE: 2
  CHAINMAIL_LEGGINGS: 2
  CHAINMAIL_BOOTS: 2

  IRON_HELMET: 3
  IRON_CHESTPLATE: 3
  IRON_LEGGINGS: 3
  IRON_BOOTS: 3

  GOLD_HELMET: 4
  GOLD_CHESTPLATE: 4
  GOLD_LEGGINGS: 4
  GOLD_BOOTS: 4

  DIAMOND_HELMET: 5
  DIAMOND_CHESTPLATE: 5
  DIAMOND_LEGGINGS: 5
  DIAMOND_BOOTS: 5

  NETHERITE_HELMET: 6
  NETHERITE_CHESTPLATE: 6
  NETHERITE_LEGGINGS: 6
  NETHERITE_BOOTS: 6

# --------------- weapons ----------------

  STONE_SWORD: 1
  IRON_SWORD: 2
  GOLD_SWORD: 3
  DIAMOND_SWORD: 4
  NETHERITE_SWORD: 5

  STONE_AXE: 1
  IRON_AXE: 2
  GOLD_AXE: 3
  DIAMOND_AXE: 4
  NETHERITE_AXE: 5

  BOW: 2
  CROSSBOW: 3
  TRIDENT: 5

# --------------- misc ----------------

  SHIELD: 4